export const MyWorks = [
  {
    id: 1,
    Image: "/website-photo2.png",
    title: "E-Commerce RoyalCart (fullStack)",
    category: "Full-Stack",
    liveLink: "https://full-stack-client-e-commerce.vercel.app/",
    git: "https://github.com/RobiMankhinStart/FullStack-E_Commerce",
  },
  {
    id: 2,
    Image: "/trimlink1.png",
    title: "TrimLink (FullStack)",
    category: "Full-Stack",
    liveLink: "https://github.com/RobiMankhinStart/TrimLink",
    git: "https://github.com/RobiMankhinStart/TrimLink",
  },
  {
    id: 3,
    Image: "/E_Scooter.png",
    title: "E-Scooter Store",
    category: "FrontEnd",
    liveLink: "https://github.com/RobiMankhinStart/Exclusive",
    git: "https://github.com/RobiMankhinStart/Exclusive",
  },

  {
    id: 4,
    Image: "/nexton.png",
    title: "Nexton E-Commerce",
    category: "FrontEnd",
    liveLink: "https://nexton-e.netlify.app/",
    git: "https://github.com/RobiMankhinStart/Nexton_-React-",
  },
  {
    id: 5,
    Image: "/plantyX.png",
    title: "PlantyX",
    category: "FrontEnd",
    liveLink: "https://github.com/RobiMankhinStart/PlantyX",
    git: "https://github.com/RobiMankhinStart/PlantyX",
  },
  {
    id: 6,
    Image: "/Marquess.png",
    title: "The Marquess Estate",
    category: "Raw JavaScript",
    liveLink: "https://marquessestate.netlify.app/",
    git: "https://github.com/RobiMankhinStart/Contest_Project",
  },
  {
    id: 7,
    Image: "/guess_it.png",
    title: "Guess It",
    category: "Raw JavaScript",
    liveLink: "https://picknum.netlify.app/",
    git: "https://github.com/RobiMankhinStart/Guess_it/",
  },
  {
    id: 8,
    Image: "/Screenshot_VTodo.png",
    title: "Vanilla ToDo",
    category: "Raw JavaScript",
    liveLink: "https://robimankhinstart.github.io/VanillaToDo/",
    git: "https://github.com/RobiMankhinStart/VanillaToDo",
  },
];
